### ISSUE TITLE
POKEMON Y CRASH EVEN NOT ENABLE JIT

### ISSUE THREAD

**Issue by yeugiangg** [emuPlace/emuThreeDS#306] opened 2023-09-04 07:12 UTC
I have a problem with Pokemon Y. It always crash even I disable JIT. My device is Iphone X and IOS version is 16.3.1. My Emu3ds setting contain: 
- CPU clock 150%
- Resolution 2000p - 1600px1200p
- Portrait layout is portrait
- Landscape layout is landscape
Can you guys help me to fix this. Thank you guys!

**Comment by pythonr0ck** [comment] 2023-09-05 01:45
Set cpu clock to 100%, also your device is a bit old. 1.0.6.4 performs a bit better for me so I’d try that. Here’s the duplicate of 1.0.6.4 ipa so you can have both versions of emuThreeDS to compare the performance. Turning off HW Shaders reduces crashes and the texture glitches in Pokemon games as well.
https://www.dropbox.com/scl/fi/qc8m952cwvhab47so7pxc/emuThreeDS_v1.0.6_Duplicate.ipa?rlkey=c6e2fj47s30c76ane6fxhi9jz&dl=1

**Closed** 2023-09-07 12:16 UTC
