### ISSUE TITLE
Install error (TrollStore)

### ISSUE THREAD

**Issue by CharlieKreig** [emuPlace/emuThreeDS#254] opened 2023-08-04 20:47 UTC
![image](https://github.com/emuPlace/emuThreeDS/assets/99195826/d2849454-6fd0-41f3-88a1-33970958ca07)

Hello! Why that error is appear? Previous version installed fine. Ios 15.1, IPad Pro M1

**Comment by ChrisRyan400** [comment] 2023-08-23 21:50
I had this too, I ended up installing with sideloadly, than it works , next issue is the constant crashes when launching a game:/

**Comment by 1-Python** [comment] 2023-08-24 18:21
(Copied and pasted myselft from:
https://github.com/emuPlace/emuThreeDS/issues/265#issuecomment-1692062143)

From the changelog: https://github.com/emuPlace/emuThreeDS/blob/main/resources/markdowns/CHANGELOG.md

It says
**“Requires eSign or Sideloadly for sideloading”
“This is an issue with Xcode 15 and annoyingly now I’ve built everything with it”
so, I think that may be the issue.**

Try using scarlet, eSign or Sideloadly for sideloading to download the latest version. You can also try installing an older version of EmuThreeDS with AltStore but I think it’s better to install the latest version with Scarlet, eSign, or Sideloadly.

**Comment by CharlieKreig** [comment] 2023-08-26 22:49
> **(Newest version of EmuThreeDS supports all sideloading services again! (like AltStore, SideStore, etc)
> 
> (Here’s the link, just scroll down, no idea why this isn’t included in github:**
> 
> https://emuplace.app/emulators/emuthreeds/)
> 
> 
> 
> (Copied and pasted myselft from:
> 
> https://github.com/emuPlace/emuThreeDS/issues/265#issuecomment-1692062143)
> 
> 
> 
> From the changelog: https://github.com/emuPlace/emuThreeDS/blob/main/resources/markdowns/CHANGELOG.md
> 
> 
> 
> It says
> 
> **“Requires eSign or Sideloadly for sideloading”
> 
> “This is an issue with Xcode 15 and annoyingly now I’ve built everything with it”
> 
> so, I think that may be the issue.**
> 
> 
> 
> Try using scarlet, eSign or Sideloadly for sideloading to download the latest version. You can also try installing an older version of EmuThreeDS with AltStore but I think it’s better to install the latest version with Scarlet, eSign, or Sideloadly.

Yeah, thanks, installing new version from your link working good. But without sticks many games not playable. Or i just can't find way turn sticks on?

**Comment by CharlieKreig** [comment] 2023-08-26 23:15
> **(Newest version of EmuThreeDS supports all sideloading services again! (like AltStore, SideStore, etc)
> 
> (Here’s the link, just scroll down, no idea why this isn’t included in github:**
> 
> https://emuplace.app/emulators/emuthreeds/)
> 
> 
> 
> (Copied and pasted myselft from:
> 
> https://github.com/emuPlace/emuThreeDS/issues/265#issuecomment-1692062143)
> 
> 
> 
> From the changelog: https://github.com/emuPlace/emuThreeDS/blob/main/resources/markdowns/CHANGELOG.md
> 
> 
> 
> It says
> 
> **“Requires eSign or Sideloadly for sideloading”
> 
> “This is an issue with Xcode 15 and annoyingly now I’ve built everything with it”
> 
> so, I think that may be the issue.**
> 
> 
> 
> Try using scarlet, eSign or Sideloadly for sideloading to download the latest version. You can also try installing an older version of EmuThreeDS with AltStore but I think it’s better to install the latest version with Scarlet, eSign, or Sideloadly.

Stick enabled by switch orientation twice and only in landscape mode, but emulation very slow, strange, previous versions working faster

**Comment by ChrisRyan400** [comment] 2023-08-27 01:21
Thanks. The folder is being created now when installing with trollstore, so I’m able to add games.  Messed around with tons of settings combos. Still can’t play though. MK7 goes through all menus then when about to start race it crashes every time

**Comment by pythonr0ck** [comment] 2023-08-27 01:49
Are you on v1.0.7.1 (2) or v1.0.7.1 (1)? Antique recently released 1.0.7.1 (2) to fix an issue where the settings wouldn’t work correctly and to fix the emuThreeDS folder not showing up. Some games for me crash or lag more with HW shaders on, could you try turning it off if you have v1.0.7.1 (2)?

**Comment by CharlieKreig** [comment] 2023-08-27 01:55
> Are you on v1.0.7.1 (2) or v1.0.7.1 (1)? Antique recently released 1.0.7.1 (2) to fix an issue where the settings wouldn’t work correctly and to fix the emuThreeDS folder not showing up. Some games for me crash or lag more with HW shaders on, could you try turning it off if you have v1.0.7.1 (2)?

I'm on 1.0.7.1(2) and hw shaders off. In this version on your device games like pokemons running normally without hw shaders?

**Comment by pythonr0ck** [comment] 2023-08-27 01:58
Yes. I meant to delete that comment though.

**Comment by ChrisRyan400** [comment] 2023-08-27 02:16
I’m on 107.1(2), it did fix the issue of
the emuthreeds folder not showing up, but I’ve tried with hw shaders, without, with JIT, without…and every other combo I tried resulted in the crash

**Comment by pythonr0ck** [comment] 2023-08-28 14:28
Does MK7 work for you in older versions of emuThreeDS? Or have you only tried 1.0.7 (2)? I’m not really sure why you are crashing but it could be that your device is too weak for some of the games. For now you might have to use an older version of emuThreeDS if that works for you. I could send over a duplicate of emuThreeDS 1.0.6.4 if you want both versions at the same time if you’d like.

**Comment by ChrisRyan400** [comment] 2023-08-29 23:42
I’m using an iPhone 11 Pro..I’ve seen other people using an XR and getting things working, I’d be surprised if its an issue with the device..the first version I tried was 1.0.6.5…nothing prior to that.

**Comment by pythonr0ck** [comment] 2023-09-01 22:09
I’m on a A13 chip as well… 1.0.6.4 performs a bit better for me so I’d try 1.0.6.4. Here’s the duplicate of 1.0.6.4 ipa so you can have both versions of emuThreeDS to compare the performance. Sorry for the late reply! https://www.dropbox.com/scl/fi/qc8m952cwvhab47so7pxc/emuThreeDS_v1.0.6_Duplicate.ipa?rlkey=c6e2fj47s30c76ane6fxhi9jz&dl=1

**Comment by pythonr0ck** [comment] 2023-09-01 22:25
If you don’t trust me and want to make a duplicate yourself:

1) Download 1.0.6.4 from the GitHub releases tab.
2) Download Documents by Readdle.
3) Copy 1.0.6.4 to the Document app.
4) Change the extension from .ipa to .zip and decompress it.
5) Open it and change the extension from .ipa to .zip
6) Open it.
7) Find and change info.plist’s extension from .plist to .txt.
8) Open it.
9) Modify “com.antique.emuThreeDS” to “com.antique.emuThreeDS2”.
10) Go back to emuThreeDS.zip and change the extension from .zip to .app again.
11) Go back 1 more time and compress the payload folder.
12) Change the payload.zip extension to .ipa

And now you’re done! You can sideload this .ipa now.

**Closed** 2023-09-07 12:15 UTC
