### ISSUE TITLE
OOT3D Crashes on game startup

### ISSUE THREAD

**Issue by AwayCoast23465** [emuPlace/emuThreeDS#299] opened 2023-08-31 23:57 UTC
I have not implemented JIT and it still crashes. any fixes? (im on a iphone 8 plus btw)

**Comment by pythonr0ck** [comment] 2023-09-01 23:17
1.0.6.4 performs a bit better for me so I’d try that. Here’s the duplicate of 1.0.6.4 ipa so you can have both versions of emuThreeDS to compare the performance and to see if it works. https://www.dropbox.com/scl/fi/qc8m952cwvhab47so7pxc/emuThreeDS_v1.0.6_Duplicate.ipa?rlkey=c6e2fj47s30c76ane6fxhi9jz&dl=1

**Comment by pythonr0ck** [comment] 2023-09-01 23:19
If you don’t trust me and want to make a duplicate yourself:

1. Download 1.0.6.4 from the GitHub releases tab.
2. Download Documents by Readdle in the App Store. (This could work in other file editor apps, but this is what I use)
3. Copy 1.0.6.4 to the Document app.
4. Change the extension from .ipa to .zip and decompress it.
5. Open it and change the extension from .ipa to .zip
6. Open it.
7. Find and change info.plist’s extension from .plist to .txt.
8. Open it.
9. Click the search icon and find “com.antique.emuThreeDS”
10. Modify it to “com.antique.emuThreeDS2”.
11. Go back to emuThreeDS.zip and change the extension from .zip to .app again.
12. Go back again and compress the payload folder.
13. Change the payload.zip extension to .ipa

And now you’re done! You can sideload this .ipa now.

(Note: After sideloading you should copy and paste the files in emuThreeDS to the new app to save your roms and save data. I’d also make a new folder in the old app, naming it old, so you can tell which app folder is which. You could also tag it.

**Closed** 2023-09-07 12:16 UTC
