### ISSUE TITLE
The game is stretched across my screen

### ISSUE THREAD

**Issue by stossy11** [emuPlace/emuThreeDS#72] opened 2023-05-18 21:56 UTC
https://imgur.com/a/i5k1ee5

Version 1.0.5.3

Controls work fine but its just wide and is wierd to play on

**Comment by arynrosh** [comment] 2023-05-20 07:58
not ideal but heres a workaround...

rotate it veriticaly
rotate it back horizontally
open the settings icon>emulation>joystick for your controls to appear as intended

hopefully it gets fixed in 1.0.6.0

**Closed** 2023-09-07 12:12 UTC
