### ISSUE TITLE
PLEASE HELP: error with Pokemon Ultra Sun

### ISSUE THREAD

**Issue by nishupad** [emuPlace/emuThreeDS#293] opened 2023-08-28 04:19 UTC
I recently downloaded the EmuThreeDS Version 1.0.7.1 (2) for my iPhone 12 Pro (iOS 16.6) from this link [https://emuplace.app/emulators/emuthreeds/] and was having no trouble running my other games. However, the problem happens when I try to run Pokemon Ultra Sun; I'm able to select my language without any issues, but then when I get to this screen...

![IMG_844AAF632B42-1](https://github.com/emuPlace/emuThreeDS/assets/80607502/7bf065dd-399d-4e81-a056-62906d914bef)

the game suddenly crashes and exits the app. 

I even tried reverting back to Version 1.0.6.5.6, but I got the same error.
 
What's going on? Is there some issue with the game  or is it a compatibility issue with my phone? More importantly, how can I fix this? Thank you in advance.

P.S. - If it makes any difference, I downloaded all my ROMs from this website: [https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Nintendo%203DS%20(Decrypted)/]. The previous ROMs I downloaded worked; only Pokemon Ultra Sun seems to have this issue.

**Comment by nishupad** [comment] 2023-08-28 14:36
> I had the same problem, just turn off HW shaders.

IT WORKED!!! THANK YOU!!! Just one last question: what settings do you recommend to reduce lag for Pokemon Ultra Sun? The game is pretty laggy, but I don't know what to turn on/off since I don't want to accidentally crash the game again.

**Comment by pythonr0ck** [comment] 2023-08-28 15:16
I would definitely recommend turning on JIT if you used a computer with AltStore or some other signing service that supports JIT to sideload. I don’t really have any good recommendations as all the settings I tried seem to preform the same. Just try turning on/off random settings to see what works for you. Just don’t turn on HW shaders and keep JIT off if you don’t have support for it because both of these settings will crash your device otherwise.

**Comment by pythonr0ck** [comment] 2023-08-28 15:20
I’ve also heard that the latest version of emuThreeDS is laggier than 1.0.6.4 maybe try downgrading if that works for you. I could send a duplicate of 1.0.6.4 if you want both versions of emuThreeDS at the same time to compare.

**Comment by nishupad** [comment] 2023-08-28 15:26
> I’ve also heard that the latest version of emuThreeDS is laggier than 1.0.6.4 maybe try downgrading if that works for you. I could send a duplicate of 1.0.6.4 if you want both versions of emuThreeDS at the same time to compare.

That would be great, thank you!

**Comment by pythonr0ck** [comment] 2023-08-28 15:31
Here’s the duplicate:
https://www.dropbox.com/scl/fi/qc8m952cwvhab47so7pxc/emuThreeDS_v1.0.6_Duplicate.ipa?rlkey=c6e2fj47s30c76ane6fxhi9jz&dl=1

**Comment by pythonr0ck** [comment] 2023-08-28 15:54
Make sure to copy and paste the files into the new app in files to keep your rooms and save data.

**Comment by nishupad** [comment] 2023-08-28 15:59
> Here’s the duplicate: https://www.dropbox.com/scl/fi/qc8m952cwvhab47so7pxc/emuThreeDS_v1.0.6_Duplicate.ipa?rlkey=c6e2fj47s30c76ane6fxhi9jz&dl=1

Got it, trying it right now and it seems to be smoother already! Thank you so much! (And yes, I copy-pasted my files into the new app.)

**Comment by pythonr0ck** [comment] 2023-08-28 16:23
No problem 👍

**Closed** 2023-09-07 12:16 UTC
